export { default as NavBar } from './NavBar/NavBar';
export { default as Landing } from './Landing/Landing';
export { default as AboutMe } from './AboutMe/AboutMe';
export { default as Education } from './Education/Education';
export { default as Skills } from './Skills/Skills';
export { default as Experience } from './Experience/Experience';
export { default as Projects } from './Projects/Projects';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer';